version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/api"
    labels:
      - "dependencies"
      - "go"
    schedule:
      interval: "daily"
    groups:
      tracing:
        patterns:
          - "go.opentelemetry.io/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "actions"
    schedule:
      interval: "daily"
    groups:
      artifacts:
        patterns:
          - "action/upload-artifact"
          - "action/download-artifact"
