name: Build 2

on:
  push:
    # this only works when the action file is on the default branch... until this gets merged respond to
    # all pushes and filter out to v20* tags in conditions
    # tags:        
    #   - v20*

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v20')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Build
        run: make build_macos_arm64
        env:
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v3
        with:
          name: flyctl-macos
          path: bin/flyctl