name: Release
on:
  push:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: echo "::error file=go.mod,line=1::Missing semicolon"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Print latest version number
        run: go run ./tools/version latest
      - name: Print next version number
        run: go run ./tools/version next
