name: Release
on:
  push:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # - name: Create annotation for build error
      #   run: echo "::error file=go.mod,line=1::Missing semicolon"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Get version numbers
        id: version
        run: |
          echo "json=$(go run ./tools/version)" >> "$GITHUB_OUTPUT"
      - name: Print version numbers
        run: |
          echo "Version JSON: ${{ steps.version.outputs.json }}"
      - name: Create tag for version
        run: |
          echo "Version JSON: ${{ fromJSON(steps.version.outputs.json).nextVersion }}"
