name: Test Installer

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - image: "ubuntu:20.04"
            setup:  apt-get update && apt-get install -y curl
        # image:
          # - "debian:oldstable-slim"
          # - "debian:stable-slim"
          # - "debian:testing-slim"
          # - "debian:sid-slim"
          # - "ubuntu:18.04"
          # - "ubuntu:20.04"
          # - "ubuntu:22.04"
          # - "ubuntu:22.10"
          # - "ubuntu:23.04"
          # - "elementary/docker:stable"
          # - "elementary/docker:unstable"
          # - "amazonlinux:latest"
          # - "archlinux:latest"
          # - "alpine:3.14"
          # - "alpine:latest"
          # - "alpine:edge"
        # deps:
        #   - curl
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash
    container:
      image: ${{ matrix.image }}
      options: --user root
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup
      run: ${{ matrix.setup }}
    - name: run installer
      run: sh ./installers/install.sh
    - run: env
    - name: check that binary is installed
      run: fly version