name: Test Installer

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-docker:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        image:
          - "ubuntu:18.04"
          - "ubuntu:20.04"
          - "ubuntu:22.04"
          - "ubuntu:22.10"
          - "ubuntu:23.04"


        # include:
        #   - image: "ubuntu:20.04"
        #     # setup:  apt-get update && apt-get install -y curl
        #   - image: "alpine:latest"
            # setup: apk --no-cache add curl
        # image:
          # - "debian:oldstable-slim"
          # - "debian:stable-slim"
          # - "debian:testing-slim"
          # - "debian:sid-slim"
          # - "ubuntu:18.04"
          # - "ubuntu:20.04"
          # - "ubuntu:22.04"
          # - "ubuntu:22.10"
          # - "ubuntu:23.04"
          # - "elementary/docker:stable"
          # - "elementary/docker:unstable"
          # - "amazonlinux:latest"
          # - "archlinux:latest"
          # - "alpine:3.14"
          # - "alpine:latest"
          # - "alpine:edge"
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash
      # FLYCTL_INSTALL: /usr/local/bin
    container:
      image: ${{ matrix.image }}
      options: --user root
    steps:
    - name: Install Dependencies (ubuntu)
      if: contains(matrix.image, 'ubuntu')
      run: |
        apt-get update && apt-get install -y curl
    - name: checkout
      uses: actions/checkout@v4
    - name: run installer
      run: sh ./installers/install.sh
    - run: |
        echo "$HOME/.fly/bin" >> $GITHUB_PATH
    - run: env
    - name: check that binary is installed
      run: |
        fly version