name: Test

on:
  workflow_call:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest-m, macos-latest-xl, windows-latest-l ]
        workdir: [ ".", "api" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "${{ matrix.workdir }}/go.mod"
      - name: Run Tests (${{ matrix.workdir }})
        working-directory: ${{ matrix.workdir }}
        run: go test ./...
