name: Test

# on:
#   push:
#   pull_request:

on:
  workflow_call:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest-m, macos-latest-xl, windows-latest-l ]
        workdir: [ ".", "api" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "${{ matrix.workdir }}/go.mod"
      - name: Run Tests (${{ matrix.workdir }})
        working-directory: ${{ matrix.workdir }}
        run: go test ./...

  # precommit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version-file: "go.mod"
  #     - uses: pre-commit/action@v3.0.0
  #       with:
  #         extra_args: --all-files --hook-stage=manual

  # lint:
  #   name: lint
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest]
  #       # TODO[md]: run this on these once the horrendous performance on macos & windows is fixed
  #       # os: [ubuntu-latest, macos-latest, windows-latest]
  #       module: [".", "api"]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version-file: "${{ matrix.module }}/go.mod"
  #         # check-latest: true
  #     - uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.54
  #         working-directory: ${{ matrix.module }}
