name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true
      - name: Run tests
        run: go test ./...
